# Generated by Django 5.0.2 on 2024-02-26 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('reason', models.CharField(choices=[('Birthday', 'День рождения'), ('Wedding', 'Свадьба'), ('Other', 'Другое')], default='Other', max_length=20, verbose_name='Повод')),
                ('description', models.TextField(verbose_name='Описание')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Запланированная сумма')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='collect_covers/', verbose_name='Обложка сбора')),
                ('finished_at', models.DateTimeField(verbose_name='Дата и время завершения сбора')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор сбора')),
            ],
            options={
                'verbose_name': 'Групповой денежный сбор',
                'verbose_name_plural': 'Групповые денежные сборы',
                'ordering': ('id',),
            },
        ),
    ]
