# Generated by Django 5.0.2 on 2024-02-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='planned_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Запланированная сумма'),
        ),
    ]
